name: 🚀 Lint, Type checking unit tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: pnpm
          node-version: 20.x

      - name: 📥 Install deps
        run: pnpm install

      - name: 🔬 Lint
        run: pnpm lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: pnpm
          node-version: 20.x

      - name: 📥 Install deps
        run: |
          pnpm install
        #   pnpm db:generate

      - name: 🔎 Type check
        run: pnpm typecheck

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: pnpm
          node-version: 20.x

      - name: 📥 Install deps
        run: pnpm install
        # run: pnpm install && pnpm db:generate

      - name: ⚡ Run vitest
        run: pnpm test:coverage
